import { User, Task, ProgressLog, Notification, ActivityItem } from '@/types';

// Seed Users
export const seedUsers: User[] = [
  {
    id: 'user-1',
    name: 'Dipanjan',
    email: 'demo.admin@collabtrack.app',
    role: 'admin',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dipanjan',
    createdAt: new Date('2024-11-01').toISOString(),
    active: true,
  },
  {
    id: 'user-2',
    name: 'Aisha',
    email: 'aisha@demo.app',
    role: 'collaborator',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    createdAt: new Date('2024-11-05').toISOString(),
    active: true,
  },
  {
    id: 'user-3',
    name: 'Rohit',
    email: 'rohit@demo.app',
    role: 'collaborator',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohit',
    createdAt: new Date('2024-11-08').toISOString(),
    active: true,
  },
];

// Seed Tasks
export const seedTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Hero Animation for Landing',
    description: 'Create an engaging hero animation using GSAP for the landing page. Include smooth transitions, scroll-triggered effects, and interactive elements.',
    assignedTo: ['user-2'],
    tags: ['animation', 'frontend'],
    status: 'in-progress',
    priority: 'high',
    estimatedHours: 8,
    deadline: new Date('2025-11-28T18:00:00Z').toISOString(),
    createdBy: 'user-1',
    createdAt: new Date('2024-11-15').toISOString(),
    updatedAt: new Date('2024-11-22').toISOString(),
  },
  {
    id: 'task-2',
    title: 'Generate 10 moodboards',
    description: 'Create diverse moodboards for the new brand identity. Include color palettes, typography samples, and visual references.',
    assignedTo: ['user-3'],
    tags: ['design', 'moodboard'],
    status: 'in-progress',
    priority: 'medium',
    estimatedHours: 10,
    deadline: new Date('2025-11-30T18:00:00Z').toISOString(),
    createdBy: 'user-1',
    createdAt: new Date('2024-11-16').toISOString(),
    updatedAt: new Date('2024-11-21').toISOString(),
  },
  {
    id: 'task-3',
    title: 'Integrate AI prompt UI',
    description: 'Build an intuitive AI prompt interface with real-time suggestions, history, and template support.',
    assignedTo: ['user-2', 'user-3'],
    tags: ['ai', 'ux'],
    status: 'todo',
    priority: 'high',
    estimatedHours: 12,
    deadline: new Date('2025-12-02T18:00:00Z').toISOString(),
    createdBy: 'user-1',
    createdAt: new Date('2024-11-18').toISOString(),
    updatedAt: new Date('2024-11-18').toISOString(),
  },
  {
    id: 'task-4',
    title: 'Polish contributor onboarding',
    description: 'Improve the onboarding documentation and create an interactive checklist for new contributors.',
    assignedTo: ['user-3'],
    tags: ['docs', 'onboarding'],
    status: 'review',
    priority: 'medium',
    estimatedHours: 5,
    deadline: new Date('2025-11-27T18:00:00Z').toISOString(),
    createdBy: 'user-1',
    createdAt: new Date('2024-11-10').toISOString(),
    updatedAt: new Date('2024-11-22').toISOString(),
  },
];

// Seed Progress Logs
export const seedProgressLogs: ProgressLog[] = [
  {
    id: 'progress-1',
    taskId: 'task-1',
    userId: 'user-2',
    date: new Date('2024-11-22').toISOString(),
    progressText: 'Completed storyboard and keyframes. Implemented GSAP timeline for hero section with smooth scroll effects.',
    percentageComplete: 40,
    hoursSpent: 3,
    attachments: [],
    feedbackStatus: 'approved',
    adminFeedback: 'Great progress! The animations look smooth.',
    createdAt: new Date('2024-11-22T14:30:00Z').toISOString(),
  },
  {
    id: 'progress-2',
    taskId: 'task-2',
    userId: 'user-3',
    date: new Date('2024-11-21').toISOString(),
    progressText: 'Created 4 moodboards with complementary color palettes. Researched typography combinations and gathered visual references.',
    percentageComplete: 40,
    hoursSpent: 4,
    attachments: [],
    feedbackStatus: 'approved',
    createdAt: new Date('2024-11-21T16:00:00Z').toISOString(),
  },
  {
    id: 'progress-3',
    taskId: 'task-4',
    userId: 'user-3',
    date: new Date('2024-11-22').toISOString(),
    progressText: 'Wrote comprehensive contributor onboarding copy. Added interactive checklist with progress tracking.',
    percentageComplete: 80,
    hoursSpent: 2,
    attachments: [],
    feedbackStatus: 'pending',
    createdAt: new Date('2024-11-22T10:00:00Z').toISOString(),
  },
  {
    id: 'progress-4',
    taskId: 'task-1',
    userId: 'user-2',
    date: new Date('2024-11-20').toISOString(),
    progressText: 'Initial setup and planning. Created wireframes and animation concepts.',
    percentageComplete: 20,
    hoursSpent: 2,
    attachments: [],
    feedbackStatus: 'approved',
    createdAt: new Date('2024-11-20T11:00:00Z').toISOString(),
  },
];

// Seed Notifications
export const seedNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-2',
    type: 'task_assigned',
    message: "New task assigned: 'Hero Animation for Landing' — Due Nov 28",
    read: true,
    payload: { taskId: 'task-1' },
    createdAt: new Date('2024-11-15T09:00:00Z').toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-3',
    type: 'deadline_approaching',
    message: "Deadline approaching for 'Polish contributor onboarding' — Due in 2 days",
    read: false,
    payload: { taskId: 'task-4' },
    createdAt: new Date('2024-11-25T08:00:00Z').toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'progress_submitted',
    message: "Aisha submitted progress for 'Hero Animation for Landing'",
    read: false,
    payload: { taskId: 'task-1', progressId: 'progress-1' },
    createdAt: new Date('2024-11-22T14:30:00Z').toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'user-2',
    type: 'progress_approved',
    message: "Your progress on 'Hero Animation for Landing' was approved",
    read: false,
    payload: { taskId: 'task-1', progressId: 'progress-1' },
    createdAt: new Date('2024-11-22T15:00:00Z').toISOString(),
  },
];

// Seed Activity
export const seedActivity: ActivityItem[] = [
  {
    id: 'activity-1',
    userId: 'user-2',
    userName: 'Aisha',
    action: 'submitted progress',
    targetType: 'progress',
    targetId: 'progress-1',
    createdAt: new Date('2024-11-22T14:30:00Z').toISOString(),
  },
  {
    id: 'activity-2',
    userId: 'user-1',
    userName: 'Dipanjan',
    action: 'approved progress',
    targetType: 'progress',
    targetId: 'progress-1',
    createdAt: new Date('2024-11-22T15:00:00Z').toISOString(),
  },
  {
    id: 'activity-3',
    userId: 'user-3',
    userName: 'Rohit',
    action: 'submitted progress',
    targetType: 'progress',
    targetId: 'progress-2',
    createdAt: new Date('2024-11-21T16:00:00Z').toISOString(),
  },
  {
    id: 'activity-4',
    userId: 'user-1',
    userName: 'Dipanjan',
    action: 'created task',
    targetType: 'task',
    targetId: 'task-3',
    createdAt: new Date('2024-11-18T10:00:00Z').toISOString(),
  },
];
